name = "dhruvilthummar-pages"
type = "javascript"
compatibility_date = "2026-01-01"

[build]
command = "npm run build:css"
cwd = "./"
watch_paths = ["assets/tailwind-input.css"]

[build.upload]
format = "service-worker"

[env.production.vars]
CONTACT_FROM = "no-reply@yourdomain.com"
CONTACT_TO = "owner@yourdomain.com"
